### ISSUE TITLE
Not possible to run examples

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/EP#4]
Using pypi version:
```
Traceback (most recent call last):
  File "C:\Tools\Miniconda\envs\ep_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Miniconda\envs\ep_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\Miniconda\envs\ep_test\lib\site-packages\ep\evaluate.py", line 253, in <module>
    evaluate.run_script(["plot_comparison.py"] + [param for param in parameters if param != ''])
  File "C:\Tools\Miniconda\envs\ep_test\lib\site-packages\ep\evalplatform\plot_comparison.py", line 365, in run_script
    if terminal_type != "svg" :
UnboundLocalError: local variable 'terminal_type' referenced before assignment
```

Using master version:
```
Traceback (most recent call last):
  File "C:\Tools\Miniconda\envs\ep_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Miniconda\envs\ep_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\MIT\Lineage\EP-master\examples\ep\evaluate.py", line 261, in <module>
    input_file_part=automatic_details_drawing_params[2] if automatic_details_drawing_params else None)
  File "C:\MIT\Lineage\EP-master\examples\ep\evalplatform\plot_comparison.py", line 358, in run
    image_sizes = draw_details.get_images_sizes(overlord, input_directory)
  File "C:\MIT\Lineage\EP-master\examples\ep\evalplatform\draw_details.py", line 235, in get_images_sizes
    return dict([(get_trailing_number(f), get_image_size_xy(get_old_path_file(f))) for f in image_list])
  File "C:\MIT\Lineage\EP-master\examples\ep\evalplatform\draw_details.py", line 235, in <listcomp>
    return dict([(get_trailing_number(f), get_image_size_xy(get_old_path_file(f))) for f in image_list])
  File "C:\MIT\Lineage\EP-master\examples\ep\evalplatform\draw_details.py", line 228, in get_image_size_xy
    shape_yx = misc.imread(filepath).shape
AttributeError: module 'scipy.misc' has no attribute 'imread'
```

**Comment by Fafa87** [comment]
For master version it is fixed: 44d8755e909f1d0f74095314ade4e76bf010b38c, 76d7c12b637169a088a6eb40f040d609e2b5d9dd
